# from https://en.wikipedia.org/wiki/Most_common_words_in_English
top_100_english_words = {
    'the': [1, 'Article'],
    'be': [2, 'Verb'],
    'to': [3, 'Preposition'],
    'of': [4, 'Preposition'],
    'and': [5, 'Conjunction'],
    'a': [6, 'Article'],
    'in': [7, 'Preposition'],
    'that': [8, 'Conjunction et al.'],
    'have': [9, 'Verb'],
    'I': [10, 'Pronoun'],
    'it': [11, 'Pronoun'],
    'for': [12, 'Preposition'],
    'not': [13, 'Adverb et al.'],
    'on': [14, 'Preposition'],
    'with': [15, 'Preposition'],
    'he': [16, 'Pronoun'],
    'as': [17, 'Adverb, conjunction, et al.'],
    'you': [18, 'Pronoun'],
    'do': [19, 'Verb, noun'],
    'at': [20, 'Preposition'],
    'this': [21, 'Determiner, adverb, noun'],
    'but': [22, 'Preposition, adverb, conjunction'],
    'his': [23, 'Possessive pronoun'],
    'by': [24, 'Preposition'],
    'from': [25, 'Preposition'],
    'they': [26, 'Pronoun'],
    'we': [27, 'Pronoun'],
    'say': [28, 'Verb et al.'],
    'her': [29, 'Possessive pronoun'],
    'she': [30, 'Pronoun'],
    'or': [31, 'Conjunction'],
    'an': [32, 'Article'],
    'will': [33, 'Verb, noun'],
    'my': [34, 'Possessive pronoun'],
    'one': [35, 'Noun, adjective, et al.'],
    'all': [36, 'Adjective'],
    'would': [37, 'Verb'],
    'there': [38, 'Adverb, pronoun, et al.'],
    'their': [39, 'Possessive pronoun'],
    'what': [40, 'Pronoun, adverb, et al.'],
    'so': [41, 'Conjunction, adverb, et al.'],
    'up': [42, 'Adverb, preposition, et al.'],
    'out': [43, 'Preposition'],
    'if': [44, 'Conjunction'],
    'about': [45, 'Preposition, adverb, et al.'],
    'who': [46, 'Pronoun, noun'],
    'get': [47, 'Verb'],
    'which': [48, 'Pronoun'],
    'go': [49, 'Verb, noun'],
    'me': [50, 'Pronoun'],
    'when': [51, 'Adverb'],
    'make': [52, 'Verb, noun'],
    'can': [53, 'Verb, noun'],
    'like': [54, 'Preposition, verb'],
    'time': [55, 'Noun'],
    'no': [56, 'Determiner, adverb'],
    'just': [57, 'Adjective'],
    'him': [58, 'Pronoun'],
    'know': [59, 'Verb, noun'],
    'take': [60, 'Verb, noun'],
    'people': [61, 'Noun'],
    'into': [62, 'Preposition'],
    'year': [63, 'Noun'],
    'your': [64, 'Possessive pronoun'],
    'good': [65, 'Adjective'],
    'some': [66, 'Determiner, pronoun'],
    'could': [67, 'Verb'],
    'them': [68, 'Pronoun'],
    'see': [69, 'Verb'],
    'other': [70, 'Adjective, pronoun'],
    'than': [71, 'Conjunction, preposition'],
    'then': [72, 'Adverb'],
    'now': [73, 'Preposition'],
    'look': [74, 'Verb'],
    'only': [75, 'Adverb'],
    'come': [76, 'Verb'],
    'its': [77, 'Possessive pronoun'],
    'over': [78, 'Preposition'],
    'think': [79, 'Verb'],
    'also': [80, 'Adverb'],
    'back': [81, 'Noun, adverb'],
    'after': [82, 'Preposition'],
    'use': [83, 'Verb, noun'],
    'two': [84, 'Noun'],
    'how': [85, 'Adverb'],
    'our': [86, 'Possessive pronoun'],
    'work': [87, 'Verb, noun'],
    'first': [88, 'Adjective'],
    'well': [89, 'Adverb'],
    'way': [90, 'Noun, adverb'],
    'even': [91, 'Adjective'],
    'new': [92, 'Adjective et al.'],
    'want': [93, 'Verb'],
    'because': [94, 'Conjunction'],
    'any': [95, 'Pronoun'],
    'these': [96, 'Pronoun'],
    'give': [97, 'Verb'],
    'day': [98, 'Noun'],
    'most': [99, 'Adverb'],
    'us': [100, 'Pronoun']}
